# Generated by Django 3.2.4 on 2021-07-01 15:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perimeters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perimeter',
            name='poly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
